
all:

  melody:
    create_user: false
    redirect_register: @oauth_register
    redirect_error: @oauth_error

    facebook:
      key: YOUR_KEY_HERE
      secret: YOUR_SECRET_HERE
      callback: @oauth_connect
      scope: [email]

    twitter:
      key: YOUR_KEY_HERE
      secret: YOUR_SECRET_HERE
      api: YOUR_API_HERE
      callback: @oauth_connect
      scope: [email]

  sf_phpopenid_plugin:
    lib_path: %SF_ROOT_DIR%/lib/vendor/php-openid
    create_user: false
    redirect_register: @openid_register
